name: egovlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.13=haa1d7c7_1
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py38h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - av==8.0.3
    - click==8.1.3
    - decord==0.6.0
    - dominate==2.6.0
    - ffmpeg==1.4
    - filelock==3.8.0
    - humanize==3.12.0
    - idna==3.4
    - joblib==1.2.0
    - numpy==1.23.5
    - opencv-python==4.6.0.66
    - packaging==21.0
    - pandas==1.1.5
    - pillow==9.3.0
    - protobuf==3.18.1
    - psutil==5.8.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - sacremoses==0.0.53
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - six==1.16.0
    - tensorboardx==2.4
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - tokenizers==0.9.4
    - torch==1.12.1+cu116
    - torchaudio==0.12.1+cu116
    - torchvision==0.13.1+cu116
    - tqdm==4.64.1
    - transformers==4.2.1
    - urllib3==1.26.12
    - --extra-index-url https://download.pytorch.org/whl/cu116
prefix: /Users/kevin/miniconda3/envs/egovlp
